<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>Booth Hacks Week 1 Challenge</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <style type="text/css">
      img {border-width: 0}
      * {font-family:'Lucida Grande', sans-serif;}
    </style>
  </head>
  <body>
    <h2>Success!</h2>
    <p>Go to <a href="https://docs.google.com/spreadsheet/ccc?key=0AskvroI9HuxydEY0b0V5MG9YYjVaM2FpMy0wUEpmQ1E&usp=sharing">the google doc</a> and fill out your (or your team's) name to claim glory (and a prize, if you're the first)</p>
    <form action="index.php" method="post" name="form3">
      <input type="submit" name="clear" value="start over">
    </form>
  </body>
</html>
